In [2]:
import numpy as np
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [9]:
# Loading the Given Cloud Point
pcd = o3d.io.read_point_cloud("cam_3_4.pcd")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

PointCloud with 1766 points.
[[ 0.81019461 -0.58799285 -6.15000582]
 [ 1.12913942 -0.40024313 -6.63102341]
 [ 0.43239903  0.27013993 -6.44182158]
 ...
 [ 0.95782048 -0.84563065 -6.63928509]
 [ 1.10642684 -0.84486693 -6.74842167]
 [ 1.6267767  -0.79402298 -6.81863689]]


In [4]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd = pcd.voxel_down_sample(voxel_size=0.05)
o3d.visualization.draw_geometries([downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

Downsample the point cloud with a voxel of 0.05


In [5]:
print("Recompute the normal of the downsampled point cloud")
downpcd.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
o3d.visualization.draw_geometries([downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024],
                                  point_show_normal=True)

Recompute the normal of the downsampled point cloud


In [6]:
print("Print a normal vector of the 0th point")
print(downpcd.normals[0])

Print a normal vector of the 0th point
[ 0.31728457 -0.16940977  0.933076  ]


In [7]:
print("Print the normal vectors of the first 10 points")
print(np.asarray(downpcd.normals)[:10, :])

Print the normal vectors of the first 10 points
[[ 0.31728457 -0.16940977  0.933076  ]
 [ 0.85930273 -0.33243588  0.38869681]
 [-0.47406665  0.07641665 -0.87716664]
 [ 0.42092626 -0.09563591  0.90203928]
 [ 0.11170747 -0.04639566  0.99265749]
 [ 0.56093526 -0.03713873  0.82702621]
 [ 0.11145788 -0.04475097  0.99276104]
 [-0.33520146 -0.93930904 -0.07306514]
 [ 0.57004418 -0.03648768  0.82080344]
 [ 0.98283347  0.1633787  -0.08570745]]


In [8]:
o3d.io.write_point_cloud("cam_3_4.pcd", downpcd)

True